// <auto-generated />
namespace DoListFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class list_items : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(list_items));
        
        string IMigrationMetadata.Id
        {
            get { return "201607052119526_list_items"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
